<?php
include('controller/gestionPosteFrame-controller.php');
?>
<div class="row" style="height:50%; overflow:auto;">
	<form id="formGestionPoste" action="controller/updatePoste.php" method="POST" onsubmit="return validateForm()" style="height:100%;">
		<div class="col-md-6" style="height:100%;">
			<?php
			include('views/gestionPosteLeft-view.php');
			?>
		</div>
		<div class="col-md-3" style="height:100%;">

			<!-- Image Map Generated by http://www.image-map.net/ -->
			<img src="img/frame.JPG"  style="max-width:100%; max-height:100%;padding:5px 0px;display: block; margin: auto;" usemap="#imgmap2017322155332">

			<map id="imgmap2017322155332" name="imgmap2017322155332">
				<area alt="Servovalve 1" title="Servovalve 1" href="#" coords="335,609,28" shape="circle" onclick="hideAll(); $('#servovalve').css('display','block');"/>
				<area alt="Servovalve 2" title="Servovalve 2" href="#" coords="388,591,25" shape="circle" onclick="hideAll(); $('#servovalve').css('display','block');"/>
				<area alt="Poste" title="Poste" href="#" coords="326,241,31" shape="circle" onclick="hideAll(); $('#posteMachine').css('display','block');"/>
				<area alt="Load Cell" title="Load Cell" href="#" coords="320,301,31" shape="circle" onclick="hideAll(); $('#loadCell').css('display','block');"/>
				<area alt="LVDT" title="LVDT" href="#" coords="304,662,20" shape="circle" onclick="hideAll(); $('#displacementCell').css('display','block');"/>
				<area alt="Accus P" title="Accus P" href="#" coords="348,661,322,770" shape="rect">
				<area alt="Accus R" title="Accus R" href="#" coords="365,747,388,639" shape="rect">
				<area alt="Manifold" title="Manifold" href="#" coords="351,561,22" shape="circle">
				<area alt="Filter P" title="Filter P" href="#" coords="345,651,363,750" shape="rect">
				<area alt="Filter R" title="Filter R" href="#" coords="388,624,408,733" shape="rect">
				<area alt="Grip" title="Grip" href="#" coords="318,499,38" shape="circle">
			</map>

		</div>
		<div class="col-md-3" style="height:100%;">
			<div class="row" style="height:90%; overflow:auto;">

				<?php
				include('views/gestionPosteRight-view.php');
				?>
			</div>
			<div class="row" id="save" style="height:10%;">
				<input type="hidden" name="id_machine" value="<?=	$poste['id_machine']	?>">
				<input type="hidden" name="id_poste" value="<?=	$poste['id_poste']	?>">
				<input type="image" alt="Submit" src="img/save.png" style="max-width:100%; max-height:100%; padding:5px 0px;display: block; margin: auto;">
			</div>

		</div>
	</form>
</div>
<div class="row" style="height:45%;">
	<?php
	include('views/gestionPosteFrameHistory-view.php');
	?>
</div>
