<?php
include('controller/gestionPosteFrame-controller.php');
?>
<div class="row" style="height:50%; overflow:auto;">
	<form id="formGestionPoste" action="controller/updatePoste.php" method="POST" onsubmit="return validateForm()" style="height:100%;">
		<div class="col-md-6" style="height:100%;">
			<?php
			include('views/gestionPosteLeft-view.php');
			?>
		</div>
		<div class="col-md-3" style="height:100%;">

			<!-- Image Map Generated by http://www.image-map.net/ -->
			<img src="img/frame2.png"  style="max-width:100%; max-height:100%;padding:5px 0px;display: block; margin: auto;" usemap="#imgmap2017322155332">

			<map id="imgmap2017322155332" name="imgmap2017322155332">
				<area alt="Frame" title="Frame" href="#" coords="10, 78, 140, 122" shape="rect"/>
				<area alt="Position" title="Position" href="#" coords="10, 123, 140, 167" shape="rect" onclick="hideAll(); $('#posteMachine').css('display','block');"/>
				<area alt="Computer" title="Computer" href="#" coords="10, 168, 141, 212" shape="rect"/>
				<area alt="Flextest / Interlock" title="Flextest / Interlock" href="#" coords="10, 213, 142, 257" shape="rect"/>
				<area alt="Load Cell" title="Load Cell" href="#" coords="10, 258, 143, 302" shape="rect" onclick="hideAll(); $('#loadCell').css('display','block');"/>
				<area alt="Heating" title="Heating" href="#" coords="10, 303, 144, 347" shape="rect"/>
				<area alt="Heating Controller" title="Heating Controller" href="#" coords="10, 348, 145, 392" shape="rect"/>
				<area alt="Strain Cell" title="Strain Cell" href="#" coords="10, 393, 146, 437" shape="rect"/>
				<area alt="Grip" title="Grip" href="#" coords="10, 438, 147, 482" shape="rect"/>
				<area alt="Displacement Cell" title="Displacement Cell" href="#" coords="10, 483, 148, 527" shape="rect" onclick="hideAll(); $('#displacementCell').css('display','block');"/>
				<area alt="Servovalve" title="Servovalve" href="#" coords="10, 528, 149, 572" shape="rect" onclick="hideAll(); $('#servovalve').css('display','block');"/>
				<area alt="Manifold" title="Manifold" href="#" coords="10, 573, 150, 617" shape="rect"/>
				<area alt="Accumulator" title="Accumulator" href="#" coords="10, 618, 151, 662" shape="rect"/>
				<area alt="Filter" title="Filter" href="#" coords="10, 663, 152, 707" shape="rect"/>

			</map>

		</div>
		<div class="col-md-3" style="height:100%;">
			<div class="row" style="height:90%; overflow:auto;">

				<?php
				include('views/gestionPosteRight-view.php');
				?>
			</div>
			<div class="row" id="save" style="height:10%;">
				<input type="hidden" name="id_machine" value="<?=	$poste['id_machine']	?>">
				<input type="hidden" name="id_poste" value="<?=	$poste['id_poste']	?>">
				<input type="image" alt="Submit" src="img/save.png" style="max-width:100%; max-height:100%; padding:5px 0px;display: block; margin: auto;">
			</div>

		</div>
	</form>
</div>
<div class="row" style="height:45%;">
	<?php
	include('views/gestionPosteFrameHistory-view.php');
	?>
</div>
